name: Build the app

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'oracle'

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZeMates.apk
          path: app/build/outputs/apk/debug/app-debug.apk